-- analytics migration removed from project.
-- The `analytics` table has been deprecated in favor of `page_views`.
-- This file kept as a placeholder to avoid reapplying the original migration.
-- If you want to fully remove this from the repository history, delete this file.